### ISSUE TITLE
Using with Play

### ISSUE THREAD

**Issue by shahrakesh** [StreetContxt/kcl-akka-stream#36]
Is it possible to use this in combination with Play framework? I tried and I am getting the below exception:

[error] c.c.k.RecordProcessorImpl - Unhandled exception in `processRecords()`, failing the streaming...
java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to scala.collection.immutable.Queue
        at scala.collection.immutable.Queue.$plus$plus(Queue.scala:111)
        at com.contxt.kinesis.ShardCheckpointTracker.watchForCompletion(RecordProcessorImpl.scala:40)
        at com.contxt.kinesis.RecordProcessorImpl.processRecords(RecordProcessorImpl.scala:118)
        at software.amazon.kinesis.lifecycle.ProcessTask.callProcessRecords(ProcessTask.java:200)
        at software.amazon.kinesis.lifecycle.ProcessTask.call(ProcessTask.java:141)
        at software.amazon.kinesis.lifecycle.ShardConsumer.executeTask(ShardConsumer.java:327)
        at software.amazon.kinesis.lifecycle.ShardConsumer.processData(ShardConsumer.java:313)
        at software.amazon.kinesis.lifecycle.ShardConsumer.handleInput(ShardConsumer.java:146)
        at software.amazon.kinesis.lifecycle.ShardConsumerSubscriber.onNext(ShardConsumerSubscriber.java:156)
        at software.amazon.kinesis.lifecycle.ShardConsumerSubscriber.onNext(ShardConsumerSubscriber.java:35)
[error] c.c.k.RecordProcessorImpl - Unhandled exception in `processRecords()`, failing the streaming...
java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to scala.collection.immutable.Queue
        at scala.collection.immutable.Queue.$plus$plus(Queue.scala:111)
        at com.contxt.kinesis.ShardCheckpointTracker.watchForCompletion(RecordProcessorImpl.scala:40)
        at com.contxt.kinesis.RecordProcessorImpl.processRecords(RecordProcessorImpl.scala:118)
        at software.amazon.kinesis.lifecycle.ProcessTask.callProcessRecords(ProcessTask.java:200)
        at software.amazon.kinesis.lifecycle.ProcessTask.call(ProcessTask.java:141)
        at software.amazon.kinesis.lifecycle.ShardConsumer.executeTask(ShardConsumer.java:327)
        at software.amazon.kinesis.lifecycle.ShardConsumer.processData(ShardConsumer.java:313)
        at software.amazon.kinesis.lifecycle.ShardConsumer.handleInput(ShardConsumer.java:146)
        at software.amazon.kinesis.lifecycle.ShardConsumerSubscriber.onNext(ShardConsumerSubscriber.java:156)
        at software.amazon.kinesis.lifecycle.ShardConsumerSubscriber.onNext(ShardConsumerSubscriber.java:35)

**Comment by shahrakesh** [comment]
Wrong scala version!
